### ISSUE TITLE
Newbie to node red

### ISSUE THREAD

**Issue by stofakiller** [ratatyq/node-red-contrib-xiaomi-smart-home#1]
Hi,

What block do i have to have on the left side so i can connect it to my gateway, or could you provide an example on connecting it to my temp/humidity sensors?

Regards

**Comment by mafof** [comment]
i'll created only listener which can run commands in input and give data status of devices. for example:
`[{"id":"d40157bd.cd4888","type":"xiaomi-smart-home","z":"3e05fa.e3f7ea06","name":"","password":"your_password","gateway":false,"switch":true,"cube":true,"sensor_ht":true,"motion":true,"magnet":true,"Wrieless_switch":true,"Wrieless_switch_two":true,"otherDevice":true,"x":685,"y":266,"wires":[[]]},{"id":"f63264.3925ada","type":"inject","z":"3e05fa.e3f7ea06","name":"Rgb on","topic":"","payload":"{\"model\":\"gateway\",\"sid\":\"yourSid\",\"command\":\"rgb\",\"value\":1694434304}","payloadType":"json","repeat":"","crontab":"","once":false,"x":299,"y":243,"wires":[["d40157bd.cd4888"]]},{"id":"1c12781c.65a648","type":"inject","z":"3e05fa.e3f7ea06","name":"Rgb off","topic":"","payload":"{\"model\": \"gateway\", \"sid\": \"yourSid\", \"command\": \"rgb\", \"value\": 0}","payloadType":"json","repeat":"","crontab":"","once":false,"x":299,"y":282,"wires":[["d40157bd.cd4888"]]},{"id":"ccd0cb99.932018","type":"inject","z":"3e05fa.e3f7ea06","name":"plug on","topic":"","payload":"{\"model\":\"86plug\",\"sid\":\"yourSid\",\"command\":\"status\",\"value\": \"on\"}","payloadType":"json","repeat":"","crontab":"","once":false,"x":306,"y":362,"wires":[["d40157bd.cd4888"]]}]`
