### ISSUE TITLE
Xiaomi node stops listening after apr. 48h

### ISSUE THREAD

**Issue by M0ebiu5** [ratatyq/node-red-contrib-xiaomi-smart-home#2]
After a few days, the xiaomi node stops listening. It is still possible to send commands, but no events are registered anymore. A restart of node red solves the problem.

A fixed interval to reestablish the listener every x hours or some kind of watchdog mechanism (eg gateway heartbeat messages) would be nice.

**Comment by mafof** [comment]
hmm, i'll not notice stoped listening. Most likely the problem is on your side.
