### ISSUE TITLE
Replicate your node with a UDP sender

### ISSUE THREAD

**Issue by matt-benett** [ratatyq/node-red-contrib-xiaomi-smart-home#3]
This is not a issue with your code, but its a problem you have solved.

Please, do you know how I can use a Inject and a UDP Output node to send a command to the gateway, the same way your sender does?

I can get it working with your plugin, but not stand alone.

`[{"id":"4f9418f5.05ef9","type":"inject","z":"14634c6e.e9a2a4","name":"","topic":"","payload":"{\"Cmd\":\"write\",\"model\":\"gateway\",\"sid\":\"aaabbbcccdddd\",\"short_id\":0,\"key\":\"8\",\"data\":\"{        \\\"rgb\\\" : 4286578816,        \\\"key\\\" : \\\"9999888887777766665555\\\"    }\"}","payloadType":"json","repeat":"","crontab":"","once":false,"x":376,"y":648,"wires":[["51466001.22c5b8","f46d1950.25ce2"]]},{"id":"51466001.22c5b8","type":"debug","z":"14634c6e.e9a2a4","name":"","active":true,"console":"false","complete":"false","x":642,"y":692,"wires":[]},{"id":"f46d1950.25ce2","type":"udp out","z":"14634c6e.e9a2a4","name":"","addr":"192.168.1.1","iface":"","port":"9898","ipv":"udp4","outport":"","base64":false,"multicast":"false","x":686,"y":620,"wires":[]}]`

**Comment by mafof** [comment]
You not send data due absence encryption and handshakes
