### ISSUE TITLE
Нормальный пример

### ISSUE THREAD

**Issue by arozhankov** [ratatyq/node-red-contrib-xiaomi-smart-home#6]
Сделайте нормальный пример. 

Не этот набор из непонятных свойств, а то, что нормально (понятно и адекватно) опишет, как пользоваться этой палитрой.

Почему вы игнорируете нормальное описание своей программы?

**Comment by wbrapist** [comment]
СОГЛАСЕН. ЭТО ПРОСТО ТРЭШ!

**Comment by wbrapist** [comment]
НЕ БЕРИТЕ ЕГО НА РАБОТУ. ЭТО ПРОСТО НУЛЕВЫЙ РАЗРАБОТЧИК

**Comment by mafof** [comment]
На мой субъективный взгляд все предельно понятно, в конце представлен пример использования данного плагина. Если вам нужен плагин с дополнительными блоками, то обратите внимание на этот [репозиторий](https://github.com/igdr/node-red-contrib-xiaomi-smart-devices)

**Comment by arozhankov** [comment]
В том и дело, что только на "ваш субъективный взгляд"...

По указанному репозитарию еще больший "предельно понятный" кодер, который не удосужился даже код в пример добавить, обойдясь скриншотом... /facepalm/

**Comment by mafof** [comment]
Прошу заметить что мы говорим об open source проектах, и если вам что то не нравиться, то вы всегда можете сделать Fork себе и исправить что то, а так же предложить изменения в основной проект.

**Comment by mafof** [comment]
Раздел issuse нужен что бы предлагать изменения, а так же сообщать о багах проекта, но не как не для обсуждения проекта.
